package message;

public enum MessageIdentifier {
	PERSISTENCE_INVALID_MODEL, 
	PERSISTENCE_INVALID_STATE,
	SECURITY_INVALID_LOGIN, 
	CLIENT_NAME, 
	CLIENT_DEBT, 
	USER_NAME, 
	USER_PASSWORD;
}
